/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */


export interface paths {
  "/api/v1/auth/token/": {
    /**
     * @description Takes a set of user credentials and returns an access and refresh JSON web
     * token pair to prove the authentication of those credentials.
     */
    post: operations["v1_auth_token_create"];
  };
  "/api/v1/auth/token/refresh/": {
    /**
     * @description Takes a refresh type JSON web token and returns an access type JSON web
     * token if the refresh token is valid.
     */
    post: operations["v1_auth_token_refresh_create"];
  };
  "/api/v1/marketing/admin/waitlist/": {
    /** @description Admin-only read access to the waitlist queue. */
    get: operations["v1_marketing_admin_waitlist_list"];
  };
  "/api/v1/marketing/admin/waitlist/{id}/approve/": {
    /** @description Admin action to approve a waiting user and generate an invite link. */
    post: operations["v1_marketing_admin_waitlist_approve_create"];
  };
  "/api/v1/marketing/waitlist/": {
    /** @description Unauthenticated endpoint for users to join the waitlist. */
    post: operations["v1_marketing_waitlist_create"];
  };
  "/api/v1/shops/claim/": {
    /**
     * @description Step 1 of Merchant Onboarding.
     * User provides their invite token, desired subdomain, and password.
     */
    post: operations["v1_shops_claim_create"];
  };
}

export type webhooks = Record<string, never>;

export interface components {
  schemas: {
    /**
     * @description * `PENDING` - Pending
     * * `APPROVED` - Approved
     * * `REJECTED` - Rejected
     * * `CLAIMED` - Claimed
     * @enum {string}
     */
    StatusEnum: "PENDING" | "APPROVED" | "REJECTED" | "CLAIMED";
    TokenObtainPair: {
      email: string;
      password: string;
      access: string;
      refresh: string;
    };
    TokenRefresh: {
      access: string;
      refresh: string;
    };
    WaitlistEntry: {
      id: number;
      /** Format: email */
      email: string;
      phone_number: string;
      survey_data?: unknown;
      status: components["schemas"]["StatusEnum"];
      /** Format: date-time */
      created_at: string;
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}

export type $defs = Record<string, never>;

export type external = Record<string, never>;

export interface operations {

  /**
   * @description Takes a set of user credentials and returns an access and refresh JSON web
   * token pair to prove the authentication of those credentials.
   */
  v1_auth_token_create: {
    requestBody: {
      content: {
        "application/json": components["schemas"]["TokenObtainPair"];
        "application/x-www-form-urlencoded": components["schemas"]["TokenObtainPair"];
        "multipart/form-data": components["schemas"]["TokenObtainPair"];
      };
    };
    responses: {
      200: {
        content: {
          "application/json": components["schemas"]["TokenObtainPair"];
        };
      };
    };
  };
  /**
   * @description Takes a refresh type JSON web token and returns an access type JSON web
   * token if the refresh token is valid.
   */
  v1_auth_token_refresh_create: {
    requestBody: {
      content: {
        "application/json": components["schemas"]["TokenRefresh"];
        "application/x-www-form-urlencoded": components["schemas"]["TokenRefresh"];
        "multipart/form-data": components["schemas"]["TokenRefresh"];
      };
    };
    responses: {
      200: {
        content: {
          "application/json": components["schemas"]["TokenRefresh"];
        };
      };
    };
  };
  /** @description Admin-only read access to the waitlist queue. */
  v1_marketing_admin_waitlist_list: {
    responses: {
      200: {
        content: {
          "application/json": components["schemas"]["WaitlistEntry"][];
        };
      };
    };
  };
  /** @description Admin action to approve a waiting user and generate an invite link. */
  v1_marketing_admin_waitlist_approve_create: {
    parameters: {
      path: {
        id: number;
      };
    };
    responses: {
      /** @description No response body */
      200: {
        content: never;
      };
    };
  };
  /** @description Unauthenticated endpoint for users to join the waitlist. */
  v1_marketing_waitlist_create: {
    requestBody: {
      content: {
        "application/json": components["schemas"]["WaitlistEntry"];
        "application/x-www-form-urlencoded": components["schemas"]["WaitlistEntry"];
        "multipart/form-data": components["schemas"]["WaitlistEntry"];
      };
    };
    responses: {
      201: {
        content: {
          "application/json": components["schemas"]["WaitlistEntry"];
        };
      };
    };
  };
  /**
   * @description Step 1 of Merchant Onboarding.
   * User provides their invite token, desired subdomain, and password.
   */
  v1_shops_claim_create: {
    responses: {
      /** @description No response body */
      200: {
        content: never;
      };
    };
  };
}
